### ISSUE TITLE
conda recipe "outputs" section cannot be parsed

### ISSUE THREAD

**Issue by woutdenolf** [marcelotrevisani/souschef#52]
```
from souschef.recipe import Recipe

recipe = Recipe()
outputs = [{"name": "package1"}, {"name": "package2"}]
recipe.add_section({"outputs": outputs})
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/denolf/.pyenv/ubuntu_20_04/versions/3.8.5/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/denolf/dev/souschef/src/souschef/mixins.py", line 337, in add_section
    self[key] = value
  File "/home/denolf/dev/souschef/src/souschef/mixins.py", line 196, in __setitem__
    self[key].append(i)
  File "/home/denolf/dev/souschef/src/souschef/ingredient.py", line 117, in append
    self.insert(len(self), value)
  File "/home/denolf/dev/souschef/src/souschef/mixins.py", line 262, in insert
    is_comment = re.match(r"^\s*#", value) is not None
  File "/users/denolf/.pyenv/ubuntu_20_04/versions/3.8.5/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Comment by woutdenolf** [comment]
Need for https://github.com/conda-incubator/grayskull/pull/341

**Comment by marcelotrevisani** [comment]
indeed, gonna take a look at it
