### ISSUE TITLE
Bug: comment in list

### ISSUE THREAD

**Issue by woutdenolf** [marcelotrevisani/souschef#54]
```python
from souschef.recipe import Recipe

recipe = Recipe()
data = {
    "requirements": {
        "run": [
            "python >=3.8",
            "# Extra: diagnostics",
            "jinja2",
        ]
    }
}
recipe.add_section(data)
```

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    recipe.add_section(data)
  File "/users/denolf/.pyenv/ubuntu_20_04/versions/3.8.5/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/mixins.py", line 338, in add_section
    self[key] = value
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/mixins.py", line 192, in __setitem__
    self[key][k] = v
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/mixins.py", line 196, in __setitem__
    self[key].append(i)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/ingredient.py", line 117, in append
    self.insert(len(self), value)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/mixins.py", line 272, in insert
    self.__add_comment_to_list(pos, value)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/mixins.py", line 310, in __add_comment_to_list
    self[pos].inline_comment.value += f"{NEW_LINE}{value}"
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by marcelotrevisani** [comment]
can you use it like:
```python
from souschef.recipe import Recipe

recipe = Recipe()
data = {
        "run": [
            "python >=3.8",
            "# Extra: diagnostics",
            "jinja2",
        ]
}
recipe["requirements"] = data
```

**Comment by marcelotrevisani** [comment]
funny
it works with a list of just one element
yeah, that is a bug, gonna take a look at it later on, thanks for reporting it

**Comment by marcelotrevisani** [comment]
actually, the problem seems to be related to the comment. gonna fix it , thanks
